name: Zig release CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goto-bus-stop/setup-zig@v1
      with:
        version: 0.8.0
    - run: sudo apt install curl libpcre++-dev
    - run: zig build
