name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - run: sudo apt install -y libcurl4-openssl-dev libpcre++-dev
      - run: zig build
      - run: zip fastfec-linux-x86_64-${{ steps.get_version.outputs.VERSION }}.zip zig-out/bin/fastfec
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fastfec-linux-x86_64-${{ steps.get_version.outputs.VERSION }}.zip
  build-macos:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - run: brew install pkg-config curl pcre
      - run: zig build
      - run: zip fastfec-macos-x86_64-${{ steps.get_version.outputs.VERSION }}.zip zig-out/bin/fastfec
      - run: zig build -Dtarget=aarch64-macos
      - run: zip fastfec-macos-aarch64-${{ steps.get_version.outputs.VERSION }}.zip zig-out/bin/fastfec
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fastfec-macos-x86_64-${{ steps.get_version.outputs.VERSION }}.zip
            fastfec-macos-aarch64-${{ steps.get_version.outputs.VERSION }}.zip
  build-windows:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - run: c:; cd \vcpkg; git pull; .\bootstrap-vcpkg.bat
      - run: vcpkg integrate install
      - run: vcpkg install pcre curl --triplet x64-windows-static
      - run: zig build --search-prefix C:/vcpkg/packages/curl_x64-windows-static --search-prefix C:/vcpkg/packages/pcre_x64-windows-static --search-prefix C:/vcpkg/packages/zlib_x64-windows-static -Dtarget=x86_64-windows-msvc
      - run: Compress-Archive zig-out/bin/fastfec.exe fastfec-windows-x86_64-${{ steps.get_version.outputs.VERSION }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fastfec-windows-x86_64-${{ steps.get_version.outputs.VERSION }}.zip
