name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-linux:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - run: sudo apt install -y libcurl4-openssl-dev libpcre++-dev
      - run: zig build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/bin/zig
  build-macos:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - run: brew install pkg-config curl pcre
      - run: zig build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/bin/zig
  build-windows:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.9.0-dev.1675+3d528161c
      - run: c:; cd \vcpkg; git pull; .\bootstrap-vcpkg.bat
      - run: vcpkg integrate install
      - run: vcpkg install pcre curl --triplet x64-windows-static
      - run: zig build --search-prefix C:/vcpkg/packages/curl_x64-windows-static --search-prefix C:/vcpkg/packages/pcre_x64-windows-static --search-prefix C:/vcpkg/packages/zlib_x64-windows-static -Dtarget=x86_64-windows-msvc
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: zig-out/bin/zig.exe
